modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/WoolButtons/blob/1.19/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolButtons/issues"

[[mods]]
	modId="sbmwoolbuttons"
	version="${file.jarVersion}"
	displayName="Wool Buttons"
	description='''Adds buttons made of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-buttons"
	authors="bl4ckscor3, DarkGuardsman"

[[dependencies.sbmwoolbuttons]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"