modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/WoolButtons/blob/1.20.4/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolButtons/issues"

[[mods]]
	modId="sbmwoolbuttons"
	version="${file.jarVersion}"
	displayName="Wool Buttons"
	description='''Adds buttons made of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-buttons"
	authors="bl4ckscor3, DarkGuardsman"

[[dependencies.sbmwoolbuttons]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.40-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"