modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/WoolButtons/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolButtons/issues"

[[mods]]
	modId="sbmwoolbuttons"
	version="${file.jarVersion}"
	displayName="Wool Buttons"
	description='''Adds buttons made of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-buttons"
	authors="bl4ckscor3, DarkGuardsman"

[[dependencies.sbmwoolbuttons]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"