license="MIT https://github.com/bl4ckscor3/WoolButtons/blob/26.1/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolButtons/issues"

[[mods]]
	modId="sbmwoolbuttons"
	version="${file.jarVersion}"
	displayName="Wool Buttons"
	description='''Adds buttons made of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-buttons"
	authors="bl4ckscor3, DarkGuardsman"

[[dependencies.sbmwoolbuttons]]
    modId="neoforge"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"